[build]
  command = "npm run build"
  # publish = ".next"

[dev]
  command = "npm run dev"
  # publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
